### ISSUE TITLE
Dataset and Pretrained models

### ISSUE THREAD

**Issue by angelacast135** [aayushbansal/Recycle-GAN#1]
Does the flower-to-flower dataset should contain consecutive images of the same flower to consecutive images of another different flower, or the domain translation is a set of images of different flowers that for instance are opening to a set of images of different flowers that are closing? In the case of face-to-face, you train a model that just goes from Obama to Trump? Also, can you please share the pretrained models for face-to-face and flower-to-flower approaches?

**Comment by jeasinema** [comment]
+1, waiting for dataset and pre-trained model

**Comment by yceugenelai** [comment]
Hi guys,
to test the recycle-gan code, I wrote a simple tool to convert video to a concatenated image sequence for creating the training dataset.
if you want to try that, you can find the tool by search the name "video_to_concatenated_image_sequence_tool" in github

**Comment by aayushbansal** [comment]
I have updated the README, and provided links to the data. Hope it is helpful. Thanks!

**Comment by angelacast135** [comment]
Thank you. According to the given splits, why does the training data looks very similar to the test data?

**Comment by emigmo** [comment]
totally agree with @angelacast135, you should double-check your training-testing set split. If you actually train your model on testing set, you may need to comment on that.

**Comment by aayushbansal** [comment]
Please see Section 4.2 (Flower to Flower) in the paper -- https://arxiv.org/pdf/1808.05174.pdf

"Extending from faces and other traditional translations,
we demonstrate our approach for flowers. We extracted the time-lapse of various
flowers from publicly available videos. The time-lapses show the blooming of different flowers but without any sync. We use our approach to align the content, i.e. both flowers bloom or die together."

**Comment by ak9250** [comment]
@aayushbansal are you looking to release the pretrained model? thanks
