### ISSUE TITLE
quantitative analysis

### ISSUE THREAD

**Issue by c1enyang** [aayushbansal/Recycle-GAN#3]
Hi,
thanks for releasing the code. could you release the evaluation code for the quantitative analysis (Image-to-Labels and Labels-to-Image) in your paper?

**Comment by c1enyang** [comment]
Waiting for your replay.

**Comment by aayushbansal** [comment]
Ok. I will update the git repo.

**Comment by c1enyang** [comment]
It's been a while since you said to update the git repo. How's that going? I'll really appreciate if you will update the git repo as soon as possible
