### ISSUE TITLE
Correct command to run on ObamaTrump data for best results

### ISSUE THREAD

**Issue by wanshun123** [aayushbansal/Recycle-GAN#9]
I've downloaded the faces dataset from https://www.dropbox.com/s/s6kzovbrevin5tr/faces.tar.gz?dl=0, resized images in the ObamaTrump folder to 128x128 (so it will be 384x128 in the train folder) and ran training on them as follows:

`nohup python train.py --dataroot ~/rgan/rgan/dataset/faces/ObamaTrumpResize --dataset_mode unaligned_triplet --model recycle_gan --which_model_netP unet_128 --which_model_netG unet_128 --fineSize 128 --loadSize 128 --name testbatch4-128size --batchSize 4
`
After 37 epochs, taking about 14 hours to train on my Quadro M4000 8GB GPU, I run test.py as follows:

`python test.py --dataroot ~/rgan/rgan/dataset/faces/ObamaTrumpResize --dataset_mode unaligned_triplet --model recycle_gan --which_model_netP unet_128 --which_model_netG unet_128 --fineSize 128 --loadSize 128 --name testbatch4-128size
`

This results in the following:

[test_latest.zip](https://github.com/aayushbansal/Recycle-GAN/files/2713931/test_latest.zip)

I've also uploaded the result at http://dataanalysis.world/recyclegan/

The resulting fake images are quite blurry and have major artefacts, especially on the Obama side. I'm wondering if there is any issue with the two commands above, especially with the `loadSize` and `fineSize` options, and if the author can share the command used to generate the Obama/Trump data in the demo.

**Comment by aayushbansal** [comment]
1. your inputs for each domain does not look correct to me. 

2. we used 'resnet_6blocks' for the flag  --which_model_netG

**Comment by iperov** [comment]
looks like RecycleGAN designed and tuned only for aayushbansal's dataset
